"""added association table as class booksehlf_book

Revision ID: 357c49a06e3d
Revises: 767f738fddc5
Create Date: 2024-02-10 15:36:41.089481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357c49a06e3d'
down_revision = '767f738fddc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('bookshelf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_bookshelf_books_book_id_books')),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], name=op.f('fk_bookshelf_books_bookshelf_id_bookshelves')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.drop_table('bookshelf_books')
    # ### end Alembic commands ###
