"""fixed bookshelves many-to-many relationship

Revision ID: 767f738fddc5
Revises: c7f7d10c3618
Create Date: 2024-02-09 19:46:40.280774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767f738fddc5'
down_revision = 'c7f7d10c3618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookshelves_book_id_books', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_bookshelves_book_id_books', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
