"""fixed bookshelf_books

Revision ID: 9a1ea60c8089
Revises: aeffdd31dafa
Create Date: 2024-02-03 13:51:50.088117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1ea60c8089'
down_revision = 'aeffdd31dafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelf_books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('bookshelf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_bookshelf_books_book_id_books')),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], name=op.f('fk_bookshelf_books_bookshelf_id_bookshelves')),
    sa.PrimaryKeyConstraint('book_id', 'bookshelf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf_books')
    # ### end Alembic commands ###
