"""initial migration

Revision ID: c2284c82d7fc
Revises: 
Create Date: 2024-02-24 16:36:15.235271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2284c82d7fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('book_cover', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_books_author_id_authors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookshelves_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('read_status', sa.Boolean(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('bookshelf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_bookshelf_books_book_id_books')),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], name=op.f('fk_bookshelf_books_bookshelf_id_bookshelves')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf_books')
    op.drop_table('bookshelves')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('authors')
    # ### end Alembic commands ###
