"""fixed bookshelves many-to-many relationship

Revision ID: c7f7d10c3618
Revises: e7ceb3dc9085
Create Date: 2024-02-09 18:04:58.485728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f7d10c3618'
down_revision = 'e7ceb3dc9085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookshelf_books')
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookshelves_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookshelves_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')

    op.create_table('bookshelf_books',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('bookshelf_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_bookshelf_books_book_id_books'),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelves.id'], name='fk_bookshelf_books_bookshelf_id_bookshelves'),
    sa.PrimaryKeyConstraint('book_id', 'bookshelf_id')
    )
    # ### end Alembic commands ###
